# language: generic

# sudo: required

# services:
#     - docker

# before_install:
#     - docker build -t tdnbbb536/react-test -f ./client/Dockerfile.dev ./client # test only client project here
#     # - docker build -t myothertest  # client以外もtestしたい場合はここに行を追加する

# scripts:
#     - docker run -e CI=true tdnbbb536/react-test npm test
#     # - docker run othertest # client以外もtestしたい場合はここに行を追加する

# after_success:
#     - docker build -t tdnbbb536/multi-client ./client
#     - docker build -t tdnbbb536/multi-nginx ./nginx
#     - docker build -t tdnbbb536/multi-server ./server
#     - docker build -t tdnbbb536/multi-worker ./worker
    
#     # Log in to the docker CLI
#     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
#     # Take those images and push them to docker hub
#     - docker push tdnbbb536/multi-client
#     - docker push tdnbbb536/multi-nginx
#     - docker push tdnbbb536/multi-server
#     - docker push tdnbbb536/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-1'
#   app: 'multi-docker'
#   env: 'MultiDocker-env'
#   bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
#   bucket_path: 'docker-multi'
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
  